version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=s2ZOqbSYSu2GRR15Wn_tiw  # Optional, use the generated one
      - KAFKA_ADVERTISED_LISTENER_EXTERNAL=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes

  producer:
    build:
      context: ./kafka-producer-app
    container_name: kafka-producer
    ports:
      - "8081:8080"
    depends_on:
      - kafka

  consumer:
    build:
      context: ./kafka-consumer-app
    container_name: kafka-consumer
    ports:
      - "8082:8080"
    environment:
      - APP_KAFKA_CONSUMER_GROUP_ID=my-group
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092  # Kafka address inside Docker
    depends_on:
      - kafka
