FROM openjdk:21-jdk-slim
WORKDIR /app
COPY target/*SNAPSHOT.jar app.jar
COPY wait-for-it.sh wait-for-it.sh
RUN chmod +x wait-for-it.sh
EXPOSE 8080
# RUN apt-get update && apt-get install -y dos2unix && dos2unix wait-for-it.sh
CMD ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]
